# Generated by Django 4.1.13 on 2025-10-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Проект ЖК', 'verbose_name_plural': 'Проекты ЖК'},
        ),
    ]
