# Generated by Django 4.1.13 on 2025-10-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(max_length=64, verbose_name='Тип'),
        ),
    ]
