# Generated by Django 4.1.13 on 2025-10-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buildings', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('area', models.CharField(max_length=64, verbose_name='Местоположение')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('status', models.CharField(choices=[('On sale', 'В продаже'), ('Sold', 'Продано'), ('Booked', 'Забронировано')], max_length=64, verbose_name='Статус')),
                ('type', models.CharField(choices=[('Flat', 'Квартира'), ('Apartments', 'Апартаменты'), ('Parking', 'Парковочное место'), ('Commercial', 'Коммерческое помещение')], max_length=64, verbose_name='Тип помещения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='buildings.building', verbose_name='Корпус')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='buildings.floor', verbose_name='Этаж')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='projects.project', verbose_name='Проект ЖК')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='buildings.section', verbose_name='Секция/подъезд')),
            ],
            options={
                'verbose_name': 'Объект собственности',
            },
        ),
    ]
