# Generated by Django 4.1.13 on 2025-10-15 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Объект собственности', 'verbose_name_plural': 'Объекты собственности'},
        ),
    ]
