# Generated by Django 4.1.13 on 2025-10-15 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_alter_property_area_alter_property_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.IntegerField(choices=[(1, 'В продаже'), (2, 'Продано'), (3, 'Забронировано')], default=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='property',
            name='type',
            field=models.CharField(choices=[('flat', 'Квартира'), ('apartments', 'Апартаменты'), ('parking', 'Парковочное место'), ('commercial', 'Коммерческое помещение')], default='flat', max_length=64, verbose_name='Тип помещения'),
        ),
    ]
