# Generated by Django 4.1.13 on 2025-10-15 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('commission_date', models.DateField(verbose_name='Срок сдачи')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Проект ЖК')),
            ],
            options={
                'verbose_name': 'Корпус',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Номер')),
                ('floor_count', models.IntegerField(verbose_name='Количество этажей')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='buildings.building', verbose_name='Корпус')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='projects.project', verbose_name='Проект ЖК')),
            ],
            options={
                'verbose_name': 'Секция/подъезд',
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='buildings.building', verbose_name='Корпус')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='projects.project', verbose_name='Проект ЖК')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='buildings.section', verbose_name='Секция/подъезд')),
            ],
            options={
                'verbose_name': 'Этаж',
            },
        ),
    ]
