# Generated by Django 4.1.13 on 2025-10-15 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='building',
            options={'verbose_name': 'Корпус', 'verbose_name_plural': 'Корпуса'},
        ),
        migrations.AlterModelOptions(
            name='floor',
            options={'verbose_name': 'Этаж', 'verbose_name_plural': 'Этажи'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'Секция/подъезд', 'verbose_name_plural': 'Секции/подъезды'},
        ),
        migrations.AlterField(
            model_name='building',
            name='number',
            field=models.CharField(max_length=64, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='floor',
            name='number',
            field=models.IntegerField(verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='section',
            name='number',
            field=models.CharField(max_length=64, verbose_name='Номер'),
        ),
    ]
