# Generated by Django 4.1.13 on 2025-10-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_type'),
        ('buildings', '0002_alter_building_options_alter_floor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='projects.project', verbose_name='Проект ЖК'),
        ),
    ]
